### ISSUE TITLE
Add simple, no db required, password reset functionality

### ISSUE THREAD

**Issue by nZac** [level12/keg-login#10]

**Comment by rsyring** [comment]
Can you elaborate on what you mean by simple & why you wouldn't want the DB to be involved?

**Comment by nZac** [comment]
Sure! [TL;DR](https://github.com/django/django/blob/master/django/contrib/auth/tokens.py#L8-L77).

There are a few things required to have a secure, simple, and database free password reset functionality. I can't say I thought of any of this and most of it is a direct rip off of Django... _something about the best ideas are stolen_.

1. It MUST identify the user, uniquely (the user email or primary key will do)
2. It MUST expire (we can get a timestamp)
3. It MUST reset the password no more than once (if the password changes the token should be invalid)
4. It MUST only change the password that was set at the time of generate (if the password change the token should be invalid)
5. It MUST only change the password if the user hasn't logged in (if the last login time is different the token should be invalid).

When compiling the token we need the following tidbits of data...

1. The users primary key or a unique ID (email could work)
2. A timestamp
3. The last time the user logged in
4. The users current password hash.

Take the ID + current password + login time + timestamp and hash and sign that and you have yourself a token.

That actually is a lot and such a system is not "easy". The solution, however, uses simple cryptographic foundations to create a really straight forward reset token which doesn't require a database storage system and can be generated functionally pure.
